---
# General

# podman install
install_podman: true

# directories
create_directories: true
directories:
  - $HOME/LibSQL/
  - $HOME/SetupFiles

# pod name
create_pod: true
pod_name: test-sql # add your podman name

# pgadmin image
pgadmin_image: docker.io/dpage/pgadmin4:latest

# pgadmin env
pgadmin_default_email: email
pgadmin_default_password: password # testing password for vagrant test deployment

# postgresql image
postgresql_image: docker.io/library/postgres:latest

# postgresql env
postgres_password: password # testing password for vagrant test deployment
postgres_user: user
