---
# General

# podman install
install_podman: true

# directories
create_directories: true
directories:
  - $HOME/Learning/LibSQL/

# volume name
# add volume for container data outside the $HOME/.local/share/containers/storage/
volume_name: LibSQL

# home directory
# add your home directory
homedir: homedir

# pod name
# add your podman name
create_pod: true
pod_name: test-sql

# pgadmin image
pgadmin_image: docker.io/dpage/pgadmin4:latest

# pgadmin env
pgadmin_default_email: email
pgadmin_default_password: password # testing password for vagrant test deployment

# postgresql image
postgresql_image: docker.io/library/postgres:latest

# postgresql env
postgres_password: password # testing password for vagrant test deployment
postgres_user: user
