---
- name: Playbook to setup test podman environment
  hosts: all
  gather_facts: false
  vars_files:
    - config.yml

  pre_tasks:
    - name: Include main playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - name: Include install configuration
      ansible.builtin.import_tasks:
        file: tasks/podman_install.yml
      when: install_podman
      tags: ["install"]

    - name: Include directories task configuration
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["dirs"]

    - name: Include podman pod setup
      ansible.builtin.import_tasks:
        file: tasks/pod_setup.yml
      when: create_pod
      tags: ["pod"]

    - name: Include container setup for pgadmin
      ansible.builtin.import_tasks:
        file: tasks/containers.yml
      tags: ["containers"]
