---
- name: Playbook to setup test podman environment
  hosts: all
  gather_facts: false
  vars_files:
    - config.yml

  pre_tasks:
    - name: Include main playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/example.config.yml"
      tags: ["always"]

  tasks:
    - name: Include install configuration
      ansible.builtin.import_tasks:
        file: tasks/podman_install.yml
      tags: ["install"]

    - name: Include directories task configuration
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["dirs"]

    #- name: Create volume
    #  containers.podman.podman_volume:
    #    state: present
    #    name: "{{ volume_name }}"
    #    options:
    #      - "device=./{{ volume_name }}"
    #      - "o=bind"

    - name: Include podman pod setup
      ansible.builtin.import_tasks:
        file: tasks/pod_setup.yml
      tags: ["pod"]
