---
- name: Playbook to setup test podman environment
  hosts: all
  gather_facts: false
  vars_files:
    - example.config.yml

  pre_tasks:
    - name: Include main playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/example.config.yml"
      tags: ["always"]

  tasks:
    - name: installing podman
      become: true
      package:
        name: "podman"
        state: present

    - name: systemctl start podman.service
      ansible.builtin.service:
        name: "podman.service"
        state: "started"
        enabled: true
      changed_when: false
      failed_when: false

    - name: create directory
      ansible.builtin.file:
        path: /home/vagrant/{{ volume_name }}
        state: directory
        mode: 0755

    - name: Create podman volume
      containers.podman.podman_volume:
        state: present
        name: "{{ volume_name }}"
        options:
          - "device=~/home/vagrant/{{ volume_name }}"

    - name: Create podman pod
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: started
        ports:
          - "9876:80"
          - "5432:5432"

    - name: Create pgadmin container
      containers.podman.podman_container:
        name: pgadmin
        image: "{{ pgadmin_image }}"
        state: started
        detach: true
        pod: "{{ pod_name }}"

    - name: Create postgresql container
      containers.podman.podman_container:
        name: db
        image: "{{ postgresql_image }}"
        state: started
        detach: true
        pod: "{{ pod_name }}"
        volume:
          - /home/vagrant/{{ volume_name }}:/var/lib/postgresql/data:Z
