---
- name: installing podman
  become: true
  package:
    name: "podman"
    state: present

- name: systemctl start podman.service
  ansible.builtin.service:
    name: "podman.service"
    state: "started"
    enabled: true
  changed_when: false
  failed_when: false
